### ISSUE TITLE
install unity and got segmentation fault (core dumped)

### ISSUE THREAD

**Issue by vergieet** [solus-project/3rd-party#106]
i install unity-editor and error segmentation fault when i run it?

**Comment by theSoenke** [comment]
I'm not able to reproduce this. Could you post the full error? Maybe the update to 5.6 already solves this https://github.com/solus-project/3rd-party/pull/152

**Comment by Dizeeee** [comment]
As far as I can tell, Unity (runtime, at least) is broken on Solus at the moment.

**Comment by ikeydoherty** [comment]
Eh Unity games were fixed not that long ago, this shouldn't be an issue anymore

**Comment by Dizeeee** [comment]
@ikeydoherty I still have crashes when running [Unturned](http://store.steampowered.com/app/304930/Unturned/) that bring down Budgie too. The screen goes black and puts me back at a gdm login screen. (Sidenote: I installed GNOME a while ago so thats why I have it, still crashed the same way before it was installed)

**Comment by ikeydoherty** [comment]
Installing it now

**Comment by Dizeeee** [comment]
Update: I just booted up Guns Of Icarus Online to check if this was Unturned or Unity, it seems to be a problem with Unturned. I'm going to play through a game to check if everything works.

**Comment by ikeydoherty** [comment]
Steam is being a twit atm ..

![screenshot from 2017-07-09 02-34-45](https://user-images.githubusercontent.com/164489/27990439-3474665e-644f-11e7-88ec-133169b72ed0.png)

**Comment by Dizeeee** [comment]
Yeah I had the same problem, it just takes time.

**Comment by Dizeeee** [comment]
@ikeydoherty just curious, what GPU do you use?

**Comment by Dizeeee** [comment]
I just made a [new issue](https://github.com/solus-project/3rd-party/issues/186) for Unturned so this doesn't get off topic.

**Comment by DataDrake** [comment]
Closing due to lack of response from the original author in over a year.
